/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package clique.again.magic.kotlin.coroutines.demo

import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test fun appHasAGreeting() {
        val classUnderTest = App()
        assertNotNull(classUnderTest.greeting, "demo should have a greeting")
    }
}
